function show(text){
	//alert(text);
	var tabs=$('#tt');
	if(text=="所有社团"){
		if(tabs.tabs('exists',"所有社团")){
			tabs.tabs('select',"所有社团");
		}else{
			tabs.tabs('add',{
				title:"所有社团",
				href:"back/manager/corporation.html",                        
				closable:true
			});
		}
	}
	if(text=="管理员管理"){
		if(tabs.tabs('exists',"管理员管理")){
			tabs.tabs('select',"管理员管理");
		}else{
			tabs.tabs('add',{
				title:"管理员管理",
				href:"back/manager/admin.html",                        
				closable:true
			});
		}
	}
	if(text=="理事会管理"){
		if(tabs.tabs('exists',"理事会管理")){
			tabs.tabs('select',"理事会管理");
		}else{
			tabs.tabs('add',{
				title:"理事会管理",
				href:"back/manager/director.html",                        
				closable:true
			});
		}
	}
	if(text=="会员管理"){
		if(tabs.tabs('exists',"会员管理")){
			tabs.tabs('select',"会员管理");
		}else{
			tabs.tabs('add',{
				title:"会员管理",
				href:"back/manager/member.html",                        
				closable:true
			});
		}
	}
	if(text=="近期活动"){
		if(tabs.tabs('exists',"近期活动")){
			tabs.tabs('select',"近期活动");
		}else{
			tabs.tabs('add',{
				title:"近期活动",
				href:"back/manager/recently.html",                        
				closable:true
			});
		}
	}
	if(text=="所有活动"){
		if(tabs.tabs('exists',"所有活动")){
			tabs.tabs('select',"所有活动");
		}else{
			tabs.tabs('add',{
				title:"所有活动",
				href:"back/manager/all.html",                        
				closable:true
			});
		}
	}
	if(text=="媒体报道"){
		if(tabs.tabs('exists',"媒体报道")){
			tabs.tabs('select',"媒体报道");
		}else{
			tabs.tabs('add',{
				title:"媒体报道",
				href:"back/manager/report.html",                        
				closable:true
			});
		}
	}
	if(text=="校园新闻"){
		if(tabs.tabs('exists',"校园新闻")){
			tabs.tabs('select',"校园新闻");
		}else{
			tabs.tabs('add',{
				title:"校园新闻",
				href:"back/manager/school.html",                        
				closable:true
			});
		}
	}
	if(text=="文档专区"){
		if(tabs.tabs('exists',"文档专区")){
			tabs.tabs('select',"文档专区");
		}else{
			tabs.tabs('add',{
				title:"文档专区",
				href:"back/manager/file.html",                        
				closable:true
			});
		}
	}
	if(text=="留影相册"){
		if(tabs.tabs('exists',"留影相册")){
			tabs.tabs('select',"留影相册");
		}else{
			tabs.tabs('add',{
				title:"留影相册",
				href:"back/manager/photo.html",                        
				closable:true
			});
		}
	}
	if(text=="社团荣誉"){
		if(tabs.tabs('exists',"社团荣誉")){
			tabs.tabs('select',"社团荣誉");
		}else{
			tabs.tabs('add',{
				title:"社团荣誉",
				href:"back/manager/honor.html",                        
				closable:true
			});
		}
	}
	if(text=="社团名人"){
		if(tabs.tabs('exists',"社团名人")){
			tabs.tabs('select',"社团名人");
		}else{
			tabs.tabs('add',{
				title:"社团名人",
				href:"back/manager/hero.html",                        
				closable:true
			});
		}
	}
	if(text=="赞助商"){
		if(tabs.tabs('exists',"赞助商")){
			tabs.tabs('select',"赞助商");
		}else{
			tabs.tabs('add',{
				title:"赞助商",
				href:"back/manager/sponsor.html",                        
				closable:true
			});
		}
	}
	if(text=="社团联系方式"){
		if(tabs.tabs('exists',"社团联系方式")){
			tabs.tabs('select',"社团联系方式");
		}else{
			tabs.tabs('add',{
				title:"社团联系方式",
				href:"back/manager/connection.html",                        
				closable:true
			});
		}
	}
	if(text=="社团留言"){
		if(tabs.tabs('exists',"社团留言")){
			tabs.tabs('select',"社团留言");
		}else{
			tabs.tabs('add',{
				title:"社团留言",
				href:"back/manager/words.html",                        
				closable:true
			});
		}
	}
}